# Generated by Django 4.2.7 on 2023-11-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testbed_emulator_backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testbedtask',
            name='assembly_type_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
