# Generated by Django 4.2.7 on 2023-11-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testbed_emulator_backend_app', '0002_testbedtask_assembly_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testbedtask',
            name='assembly_type_id',
            field=models.IntegerField(blank=True, choices=[(1, 'M'), (2, 'F'), (3, 'I')], null=True),
        ),
    ]
